language: objective-c
osx_image: xcode11.4
script:
    - xcodebuild clean build -project Rainy.xcodeproj -scheme Rainy -destination "platform=iOS Simulator,name=iPhone X,OS=13.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
